# Generated by Django 4.0.5 on 2024-02-18 14:26

import app.user_note.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.JSONField(default=app.user_note.models.get_default_content),
        ),
    ]
